package amf.core.parser

import amf.client.convert.NativeOpsFromJs

class JsAmfExpandedGraphParserTest extends ExpandedGraphParserTest with NativeOpsFromJs

class JsAmfFlattenedGraphParserTest extends FlattenedGraphParserTest with NativeOpsFromJs
