package amf.core.parser

import amf.client.convert.NativeOpsFromJvm

class JvmAmfExpandedGraphParserTest extends ExpandedGraphParserTest with NativeOpsFromJvm

class JvmAmfFlattenedGraphParserTest extends FlattenedGraphParserTest with NativeOpsFromJvm
